language: python

python:
    -   "2.7"

cache: pip

before_install:
    -   pip install -U setuptools

install:
    -   pip install -U -r ./requirements_linux.txt

before_script:
    - export PYTHONPATH=$PYTHONPATH:$PWD/Cylinder-server/
    - sudo useradd test
    - sudo echo test | passwd test --stdin
    - sudo useradd sudouser sudo
    - sudo echo sudopassword | passwd sudouser --stdin

script: 
# TDD
    - nosetests -v ./tests
# Unit tests
    - nosetests -v ./tests/unit
