language: python
python:
    -   "2.7"
before_install:
    -   sudo apt-get update
    -   pip install --upgrade setuptools
install:
    -   pip install -r ./requirements_linux.txt
script: 
# TDD
    - nosetests ./tests
    - nosetests ./tests/unit
#Unit tests (one per class)
#    - ./tests/unit/authentication.py