os:
    -   linux
    -   osx

language: python

python:
    -   "2.7"

cache: pip

env:
    -   TEST_DIR=./tests
    -   TEST_DIR=./tests/unit

before_install:
    -   pip install -U setuptools

install:
    -   sudo useradd test -M -p $(echo "test" | openssl passwd -1 -stdin)
    -   sudo useradd sudouser -M -G sudo -p $(echo "sudouser" | openssl passwd -1 -stdin)
    -   sudo usermod -a -G shadow sudouser
    -   sudo apt-get install python-pam
    -   pip install -U -r ./requirements_linux.txt

before_script:
    - export PYTHONPATH=$PYTHONPATH:$PWD/Cylinder-server/

script:
    - sudo -u sudouser -ns PATH=$PATH PYTHONPATH=$PYTHONPATH & nosetests -v $TEST_DIR

