language: python
python:
    -   "2.7"
install:
    -   ./setup.py install
script: 
# TDD
    - ./tests/test_core.py
    - ./tests/test_file_system_procedures.py
    - ./tests/test_file_content_procedures.py
    - ./tests/test_metadata_procedures.py
    
#Unit tests (one per class)
#    - ./tests/unit/authentication.py