os:
    -   linux
    -   osx

language: python

python:
    -   "2.7"

cache:
    pip: true
    directories:
        - /home/travis/virtualenv/python2.7/lib/python2.7/site-packages
        - $HOME/.pip-cache/

env:
    global:
    -   TEST_USER=test
    -   TEST_PASSWORD=test
    -   TEST_USER_DIR=/home/test

    -   SUDO_USER=sudouser
    -   SUDO_PASSWORD=sudouser
    -   SUDO_USER_DIR=/home/sudouser

    -   TEST_SRC_DIR=./tests
    -   TEST_DEST_DIR=/home/sudouser/tests

    matrix:
    -   TEST_DIR=/home/sudouser/tests
    -   TEST_DIR=/home/sudouser/tests/unit

before_install:
    -   pip install -U setuptools --download-cache $HOME/.pip-cache/

install:
    -   sudo useradd $TEST_USER -M -p $(echo $TEST_PASSWORD | openssl passwd -1 -stdin)
    -   sudo useradd $SUDO_USER -M -G sudo -p $(echo $SUDO_PASSWORD | openssl passwd -1 -stdin) -d $SUDO_USER_DIR
    -   sudo usermod -a -G shadow $SUDO_USER
    -   sudo usermod -a -G $USER $SUDO_USER
    -   sudo mkdir $SUDO_USER_DIR
    -   sudo cp -r $TEST_SRC_DIR $SUDO_USER_DIR
    -   sudo chown $SUDO_USER:$SUDO_USER -R $SUDO_USER_DIR
    -   sudo apt-get install python-pam
    -   pip install -U -r ./requirements_linux.txt --download-cache $HOME/.pip-cache/
    -   sudo ls $TEST_DEST_DIR

before_script:
    - export PYTHONPATH=$PYTHONPATH:$PWD/Cylinder-server/

script:
    - sudo -Hu sudouser -ns PATH="$PATH" PYTHONPATH="$PYTHONPATH" TEST_USER="$TEST_USER" TEST_PASSWORD="$TEST_PASSWORD" nosetests -v $TEST_DIR
