os:
    -   linux
    -   osx

language: python

python:
    -   "2.7"

cache: pip

env:
    -   TEST_DIR=./tests
    -   TEST_DIR=./tests/unit

before_install:
    -   pip install -U setuptools

install:
    -   pip install -U -r ./requirements_linux.txt

before_script:
    - export PYTHONPATH=$PYTHONPATH:$PWD/Cylinder-server/
    - sudo useradd --help
    - sudo useradd test
    #- sudo echo "test:test" | chpasswd
    - sudo useradd sudouser sudo
    #- sudo echo "sudouser:sudouser" | chpasswd

script:
    - nosetests -v $TEST_DIR
