language: python

python:
    -   "2.7"

before_install:
    -   pip install -U setuptools

install:
    -   pip install -U -r ./requirements_linux.txt

before_script:
    - export PYTHONPATH=$PYTHONPATH:$PWD/Cylinder-server/

script: 
# TDD
    - nosetests -v ./tests
# Unit tests
    - nosetests -v ./tests/unit
